<%@LANGUAGE="VBSCRIPT" CODEPAGE="65001"%>
<%
	Response.CharSet = "utf-8"
%>
<!-- #include file = "../../libs/function.asp" -->
<%
	DIM subAct, subActFile
	subAct = GetInputReplce(REQUEST.QueryString("subAct"), "")

	SELECT CASE LCASE(subAct)
	CASE "login"
		subActFile = "../comm/login.ok.asp"
	CASE "logout"
		subActFile = "../comm/logout.ok.asp"		
	CASE "defaultconfig"
		subActFile = "../default/default.config.ok.asp"
	CASE "staffsearch"
		subActFile = "../default/staff.search.asp"
	CASE "staff"
		subActFile = "../default/staff.ok.asp"
	CASE "layout"
		subActFile = "../layout/layout.ok.asp"
	CASE "jquerytree"
		subActFile = "../comm/jqueryFileTree.asp"
	CASE "swfupload"
		subActFile = "../comm/swfupload.asp"
	CASE "colorset"
		subActFile = "../comm/skin.colorset.asp"
	CASE "page"
		subActFile = "../layout/page.ok.asp"
	CASE "memberconfig"
		subActFile = "../member/member.config.ok.asp"
	CASE "memberlistbody"
		subActFile = "../member/member.list.body.asp"
	CASE "memberlist"
		subActFile = "../member/member.list.ok.asp"
	CASE "memberlistexcel"
		subActFile = "../member/member.excel.ok.asp"
	CASE "membersearch"
		subActFile = "../member/member.search.asp"
	CASE "membermodify"
		subActFile = "../member/member.modify.ok.asp"
	CASE "membermodifyupload"
		subActFile = "../member/member.modify.upload.asp"
	CASE "membercheck"
		subActFile = "../member/member.check.asp"
	CASE "membergroup"
		subActFile = "../member/member.group.ok.asp"
	CASE "memberformadd"
		subActFile = "../member/member.form.add.asp"
	CASE "memberform"
		subActFile = "../member/member.form.ok.asp"
	CASE "memberdoc"
		subActFile = "../member/member.document.ok.asp"
	CASE "memberdeniedidadd"
		subActFile = "../member/member.denied.id.add.asp"
	CASE "memberdeniedid"
		subActFile = "../member/member.denied.id.ok.asp"
	CASE "memberlevel"
		subActFile = "../member/member.level.ok.asp"
	CASE "pointconfig"
		subActFile = "../member/point.config.ok.asp"
	CASE "pointlistbody"
		subActFile = "../member/point.list.body.asp"
	CASE "memberout"
		subActFile = "../member/member.out.ok.asp"
	CASE "mailingsend"
		subActFile = "../member/mailing.send.ok.asp"
	CASE "mailinggroup"
		subActFile = "../member/mailing.group.ok.asp"
	CASE "mailinggroupmemberbody"
		subActFile = "../member/mailing.group.member.body.asp"
	CASE "mailinggroupmember"
		subActFile = "../member/mailing.group.member.ok.asp"
	CASE "mailingetc"
		subActFile = "../member/mailing.etc.ok.asp"
	CASE "message"
		subActFile = "../member/member.message.ok.asp"
	CASE "fileboxremove"
		subActFile = "../comm/filebox.remove.asp"
	CASE "fileboxbody"
		subActFile = "../comm/filebox.body.asp"
	CASE "fileboxupload"
		subActFile = "../comm/filebox.upload.asp"
	CASE "syscode"
		subActFile = "../comm/syscode.ok.asp"
	CASE "zipcode"
		subActFile = "../../libs/zipcode.asp"
	CASE "boardmake"
		subActFile = "../board/board.make.ok.asp"
	CASE "boardconfigdefault"
		subActFile = "../board/board.config.default.ok.asp"
	CASE "boardconfigaddition"
		subActFile = "../board/board.config.addition.ok.asp"
	CASE "boardconfigfield"
		subActFile = "../board/board.config.field.ok.asp"
	CASE "boardconfigcategory"
		subActFile = "../board/board.config.category.ok.asp"
	CASE "boardcategorylist"
		subActFile = "../board/board.config.category.list.asp"
	CASE "boardcategorydetail"
		subActFile = "../board/board.config.category.add.asp"
	CASE "boardcategorymove"
		subActFile = "../board/board.config.category.move.asp"
	CASE "boardadminlist"
		subActFile = "../board/board.config.admin.list.asp"
	CASE "boardconfiggrantinfo"
		subActFile = "../board/board.config.grantinfo.ok.asp"
	CASE "boardconfigpoint"
		subActFile = "../board/board.config.point.ok.asp"
	CASE "boardconfigskin"
		subActFile = "../board/board.config.skin.ok.asp"
	CASE "boardremove"
		subActFile = "../board/board.remove.asp"
	CASE "boardmanage"
		subActFile = "../board/board.manage.ok.asp"
	CASE "commentsearch"
		subActFile = "../board/comment.search.ok.asp"
	CASE "filesearch"
		subActFile = "../board/file.search.ok.asp"
	CASE "boarddocument"
		subActFile = "../board/board.document.ok.asp"
	CASE "boarddeclared"
		subActFile = "../board/board.declared.ok.asp"
	CASE "commentdeclared"
		subActFile = "../board/comment.declared.ok.asp"
	CASE "boardnotice"
		subActFile = "../board/board.notice.code.ok.asp"
	CASE "boardtrash"
		subActFile = "../board/board.trash.ok.asp"
	CASE "searchconfig"
		subActFile = "../board/search.config.ok.asp"
	CASE "schedule"
		subActFile = "../other/schedule.ok.asp"
	CASE "popup"
		subActFile = "../other/popup.ok.asp"
	CASE "notice"
		subActFile = "../comm/notice.asp"
	END SELECT

	SERVER.EXECUTE(subActFile)
%>